CREATE TABLE IF NOT EXISTS `persons` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `name` varchar(160) NOT NULL default '',
  `original_name` varchar(160) NOT NULL default '',
  `type` tinyint(3) unsigned NOT NULL default '11',
  `gender` tinyint(1) unsigned NOT NULL default '0',
  `poster_url` text NOT NULL,
  `birth_date` date NULL DEFAULT NULL,
  `birth_text` varchar(120) NOT NULL default '',
  `birth_place` varchar(255) NOT NULL default '',
  `career` varchar(255) NOT NULL default '',
  `genre` varchar(255) NOT NULL default '',
  `height` varchar(40) NOT NULL default '',
  `spouse` varchar(255) NOT NULL default '',
  `biography` mediumtext NOT NULL,
  `trivia` mediumtext NOT NULL,
  `filmography` mediumtext NOT NULL,
  `voice` mediumtext NOT NULL,
  `producer` mediumtext NOT NULL,
  `director` mediumtext NOT NULL,
  `writer` mediumtext NOT NULL,
  `awards` mediumtext NOT NULL,
  `links` mediumtext NOT NULL,
  `source_url` varchar(255) NOT NULL default '',
  `created_by` int(10) unsigned NOT NULL default '0',
  `created_at` datetime NULL DEFAULT NULL,
  `updated_by` int(10) unsigned NOT NULL default '0',
  `updated_at` datetime NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `name` (`name`),
  KEY `original_name` (`original_name`),
  KEY `birth_date` (`birth_date`),
  KEY `type` (`type`),
  KEY `updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `person_photos` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `person_id` int(10) unsigned NOT NULL default '0',
  `image_url` text NOT NULL,
  `sort` int(10) unsigned NOT NULL default '0',
  PRIMARY KEY (`id`),
  KEY `person_id` (`person_id`),
  KEY `sort` (`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
